### PR TITLE
Added Audio Input with multiple languages and Deadline with remainder

### PR DESCRIPTION
**Pull request by Prer74**

### CODE REVIEW

**Review by chavarera — CHANGES_REQUESTED** [review]
- Please Remove Cache files from all directories
- Use Code formatting tools to follow pep8 standard (Such as Black, isort, autopep8 )
- Add documentation for modules and functions

**Comment by Prer74** [comment]
I have made the following updates:

**Removed __pycache__ Directories:** Cleared all __pycache__ files for a cleaner codebase.

**Code Formatting:** Used Black to format Python files according to PEP 8 standards.

**Added Documentation:** Enhanced documentation in HTML templates and relevant models/forms for better clarity.

**Comment by chavarera** [comment]
@Prer74 

migrations/__pycache__ : still exists in directories please add it into git ignore to not track or upload to github 


sql/add.sql : this file also not required right?

**Comment by Prer74** [comment]
Can you please check it again its in feature branch.
Yes I used this sql/add.sql to delete all previous content in table, I forgot to remove!

**Comment by Prer74** [comment]
Thank You!!

**Pull request merged**
